[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
alyrasign = "9G6Skb8Enu9MhTAkJyqHBDmq6AP3jPD2RVn5svRZxDiM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/alyrasign"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
